### ISSUE TITLE
forumHasModeratorPersonCheck and queryParamsTest in LdbcDatagenTest fail

### ISSUE THREAD

**Issue by jackwaudby** [ldbc/ldbc_snb_datagen_spark#133]
In `LdbcDatagenTest` on the `dev` branch `forumHasModeratorPersonCheck` and `queryParamsTest` fail. 

This behaviour is expected given the changes we have made -- commented out for now.

**Comment by jackwaudby** [comment]
Some thoughts on dealing with the `forumHasModeratorPerson` edge. 

**Constraint: a forum must always have a single moderator.** 

In the defined delete queries there is no `removeHasModerator` query. This edge is only ever cascading-ly deleted by _**delete 1**_: remove person or **_delete 4:_** remove forum. The considerations are different for each forum type. 

`Walls`: the `hasModerator` edge is always to the creator of the forum.  `Walls` are never removed by delete 4.  Hence the only time `hasModerator:WALL` is removed is by delete 1. 

`Albums`: the `hasModerator` edge is always to the creator of the forum. `Albums ` can removed by delete 4 in which case the `hasModerator:ALBUM` edge is also removed.  This is also true of delete 1. 

**`Groups`: the edge case.** When a delete 4 is for a group then the `hasModerator:GROUP` edge is also removed. The interesting case is when a delete 1 is for a person who is the moderator of a group, the cascading delete leaves the group without a moderator breaking the constraint. 

Option 1: Insert a newHasModerator is included in a delete 1 query that removes a person who is a moderator. This makes the update to the edge atomic and the schema constraint never broken. In this case delete 1 becomes an update transaction. 

Option 2: We add an insert operation (9) for `hasModerator` that is executed at some point after the delete of moderator. This is probably the "easiest" to do but leaves some time when the constraint is violated. 

What do you think? @szarnyasg 

I think I lean towards option 1: makes for a more interesting transaction.

**Comment by jackwaudby** [comment]
The proposed solution is to have different behaviour based on the workload. 

For the _interactive_ workload the exactly 1 cardinality of the `hasModerator` edge is required, else, Short Read 6 could return a null result, which does not match LDBC's design philosophy. Thus, for the interactive workload Datagen must always produce update streams containing solely of insert operations, i.e., produces an _equivalent_ output to Datagen v0.3.3. 

For the _BI_ workload we have decided to change the schema to allow a `Forum` to have 0.. outgoing `hasModerator` edges, capturing the case when a delete 1 operation removes the moderator of a `Group` but the `Group` persists after this event without a moderator. This doesn't introduce any null result problems as no BI query utilises the `hasModerator` edge. 

This is "Option 3", the rationale bring it avoids introducing unnecessary complexity of option 1 (introducing a multi statement update transaction) and option 2 (introducing another insert operation) given the scope of the benchmark.

The change in schema across workloads will need to be reflected in the specification.

**Comment by szarnyasg** [comment]
As discussed during the meeting, the task force chose Option 3. Now we need to implement it properly.

The current version on `dev` generates dangling `hasModerator` edges, i.e. ones that point to `Person` nodes which do not exist in the network -- because they are deleted *before* the `Forum` is created

Running the generator in `rawdata` mode (with the `CsvComposite` serializer and SF0.1) reveals the problem:

```ini
generator.scaleFactor:0.1
generator.mode:rawdata
serializer.format:CsvComposite
```

```
$ ag 15393162789841 person_0_0.csv 

creationDate|deletionDate|id|firstName|lastName|gender|birthday|locationIP|browserUsed|language|email
632:2011-03-17T07:59:34.074+00:00|2012-03-06T22:43:52.032+00:00|15393162789841|Bob|Choi|male|1980-02-19|27.100.153.3|Firefox|ko;en|Bob15393162789841@gmail.com;Bob15393162789841@gmx.com

$ ag 15393162789841 forum_hasModerator_person_0_0.csv 

creationDate|deletionDate|Forum.id|Person.id
2185:2011-03-17T07:59:44.074+00:00|2012-03-06T22:43:52.032+00:00|481036339335|15393162789841
2186:2011-05-30T16:38:29.067+00:00|2019-12-30T00:00:00.000+00:00|549755816072|15393162789841
2187:2011-12-04T16:22:01.629+00:00|2019-12-30T00:00:00.000+00:00|755914246281|15393162789841
2188:2011-09-25T04:35:45.325+00:00|2019-12-30T00:00:00.000+00:00|687194769546|15393162789841
2189:2011-05-17T23:18:51.634+00:00|2019-12-30T00:00:00.000+00:00|549755816075|15393162789841

$ ag '(481036339335|549755816072|755914246281|687194769546|549755816075)' forum_0_0.csv 

creationDate|deletionDate|id|firstName|lastName|gender|birthday|locationIP|browserUsed|language|email
2185:2011-03-17T07:59:44.074+00:00|2012-03-06T22:43:52.032+00:00|481036339335|Wall of Bob Choi|WALL
2186:2011-05-30T16:38:29.067+00:00|2019-12-30T00:00:00.000+00:00|549755816072|Group for Dolly_Parton in Andong|GROUP
2187:2011-12-04T16:22:01.629+00:00|2019-12-30T00:00:00.000+00:00|755914246281|Group for Karn_Evil_9 in Andong|GROUP
2188:2011-09-25T04:35:45.325+00:00|2019-12-30T00:00:00.000+00:00|687194769546|Group for Clint_Eastwood in Andong|GROUP
2189:2011-05-17T23:18:51.634+00:00|2019-12-30T00:00:00.000+00:00|549755816075|Group for Kurt_Vonnegut in Andong|GROUP
```

Note that Person `Bob Choi` is deleted at `2012-03-06T22:43:52.032+00:00` so his node does not get into the generated non-raw (`interactive`) data set. This does not cause a problem with the `Wall of Bob Choi` as that node and its edges are simply omitted from the data set but it raises an error for the other 4 `Group for ...` Forums.

Basically resolving this requires us to tackle this TODO in the code:

https://github.com/ldbc/ldbc_snb_datagen/blob/3852dc754a369889c945e8a3317d0200aee7555a/src/main/java/ldbc/snb/datagen/generator/generators/ForumGenerator.java#L120

On paper, a possible workaround would be to change the generator so that it appoints a moderator (`Person`) who is guaranteed to "outlive" the `Forum`. However, the generator works the other way around and the `Person` nodes are passed along as follows:

* `generateActivityForBlock(..., List<Person> block)`
  * `generateActivity(Person person, ...)`
    * `generateGroups(Person person, ...)`
      * `createGroup(..., Person moderator, ...)`

This means that if we don't change the structure fundamentally, we have the following options:
* Adjust the lifespan of the `Forum` to match that of the `Person` (this is a quick and dirty hack).
* Let the serializer decide whether to serialize the `hasModerator` edge or not. This would work but leads to a bit of code duplication between the serializers as -- for the cases when the edge is serialized -- each serializer would need to work out the `deletionDate` for the edge.
* Introduce a `hasModeratorDeletionDate` attribute to the `Forum` class in the `ForumGenerator` and use this attribute to decide whether to serialize the `hasModerator` edge or not. If it is serialized, this attribute shall be serialized with it.

:warning: The `CsvMergeForeign` schema currently does not accommodate the temporal attributes of the `hasModerator` edge. So we might need to change this schema.
