### ISSUE TITLE
Missing parameter generation for LDBC SNB scale >= 300

### ISSUE THREAD

**Issue by l-hoang** [ldbc/ldbc_snb_datagen_spark#201]
When generating scale 300 and 1000 data for the SNB benchmark, the parameters for the queries do not seem to be generated in the resulting output directory. The graph itself it generated just fine.

Here is my params file for scale 300 for example.

```
ldbc.snb.datagen.generator.scaleFactor:snb.interactive.300

ldbc.snb.datagen.serializer.dynamicActivitySerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.activity.CsvCompositeDynamicActivitySerializer
ldbc.snb.datagen.serializer.dynamicPersonSerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.person.CsvCompositeDynamicPersonSerializer
ldbc.snb.datagen.serializer.staticSerializer:ldbc.snb.datagen.serializer.snb.csv.staticserializer.CsvCompositeStaticSerializer
```

I am on the stable branch (e6213b52ea). Any idea what might be causing the issue? Any help would be greatly appreciated.

**Comment by szarnyasg** [comment]
Hello @l-hoang,

What's your setup? The substitution parameter generator runs on a single machine, therefore if your setup uses many small machines, Hadoop (the graph generator) might work fine but the parameter generator might crash.

Fortunately, your problem can be worked around -- because the parameters are very slow to generate, I've uploaded them to my Dropbox, so you can just grab them:
https://www.dropbox.com/s/9eak7smwaf1342h/substitution_parameters.tar.zst?dl=1
This has SF300 and SF1000 as well.

Gabor

**Comment by szarnyasg** [comment]
Closing this due to the lack of activity. N.b. the substitution parameter generator on the `dev` branch is yet to be implemented.
