### ISSUE TITLE
Figure 2.1 does not match with the produced output

### ISSUE THREAD

**Issue by kubajal** [ldbc/ldbc_snb_datagen_spark#208]
Hi,
the field `type` in the entities: `Organisation` and `Place` is not included in Figure 2.1 (The LDBC SNB data schema) of [LDBC specification v0.3.2](https://github.com/ldbc/ldbc_snb_docs/releases/tag/v0.3.2).
In other words when I generate data using the LDBC data generator the field is there but it is not listed on the schema. That field is however listed on Figures 2.13, 2.14, 2.15 and 2.16 (they depict output format of various serializers). Shouldn't the field `type` be also shown on Figure 2.1?
I used LDBC data generator [v0.2.8](https://github.com/ldbc/ldbc_snb_datagen/releases/tag/v0.2.8), if that is relevant.
Best regards,
Jakub

**Comment by szarnyasg** [comment]
Hi @kubajal, good thanks, thanks for raising.

When serializing the graph to CSV, we perform a step similar to object-relational mapping, which involves mapping
inheritance hierarchies.

For Places, the generator uses the ["map hierarchy to a single table" ORM approach](http://agiledata.org/essays/mappingObjects.html#MapHierarchyToTable), which relies on using a [discriminator](https://www.visual-paradigm.com/support/documents/vpuserguide/3563/3564/85389_usingdiscrim.html) column/attribute. Here, we use `type` as the discriminator.

For the Message (Comment/Post) hierarchy, it uses the ["each concrete class to its own table" approach](http://agiledata.org/essays/mappingObjects.html#MapConcreteClassToTable) which requires no discriminator.

Because this happens during the mapping, I don't think the `type` belongs to the graph schema.
But I think such a short explanation would be useful when presenting the CSV schemas (headers).
What do you think?

By the way, we have recently considered adding a `type` field to Forums as well (distinguishing between Walls, Groups and Albums) but ultimately decided not to add this field as the Forum name already contains this information ("Wall of...", "Group for ...", "Album _k_ of ...") and it is currently not used by any of the queries.

**Comment by kubajal** [comment]
Hi @szarnyasg,
that is a very good explanation. Those two examples for Places and Messages you gave show the crucial difference. 
Yes, a short explanation somewhere in the document would be sufficient. I think that such a short note would help people with little knowledge of object-oriented modelling who look first at the schema in the specification and then look at the output of the generator.

**Comment by szarnyasg** [comment]
Thanks, I opened a followup issue in the docs repository.
