### ISSUE TITLE
DateTime almost conforms to RFC3339

### ISSUE THREAD

**Issue by frankmcsherry** [ldbc/ldbc_snb_datagen_spark#86]
The `DateTime` format in the docs (at the moment of submission) is
```
yyyy-mm-ddTHH:MM:ss.sss+0000
```
This *almost* conforms to [RFC3339](https://tools.ietf.org/html/rfc3339), which would require it to have a ':' between the hour and minutes of the timezone offset.
```
yyyy-mm-ddTHH:MM:ss.sss+00:00
```
I have no clue if standards compliance is a goal, but it would have helped me a bit (Rust's datetime library uses RFC3339, and needed some debugging and surgery to get your data parsed).

**Comment by szarnyasg** [comment]
Thanks for raising this issue, we'll consider it. If we make this change, it will require a bunch of adjustments in other repositories such as the [spec](https://github.com/ldbc/ldbc_snb_docs/blob/24b9d1ef9683a6fd6d7ddef3265a73d5bb2ae8c9/benchmark-specification.tex#L72) and the [reference implementations](https://github.com/ldbc/ldbc_snb_implementations/blob/e5ec590e0fb18d7f2a5218b10561a48a619a5bda/cypher/load-scripts/convert-csvs.sh#L21-L23).

**Comment by frankmcsherry** [comment]
Yup. It is probably pretty breaking for other users, so it's not obviously the right thing to do.

**Comment by szarnyasg** [comment]
I investigated this a bit. It turns out that this can be configured using the `params.ini` file:

```
ldbc.snb.datagen.serializer.formatter.StringDateFormatter.dateTimeFormat:yyyy-MM-dd'T'HH:mm:ss.SSS+00:00
```

This gives us a chance to update the format and make it simple for users to fall back to the previous version.

A lesson learnt here: initially, I thought that the `XXX` modifier will do the trick, but apparently, [_if the offset value from GMT is 0, "Z" is produced."_](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#iso8601timezone). LDBC uses GMT (and UTC wouldn't make a difference here).

```java
Calendar calendar = Calendar.getInstance();
Date date = new Date();

final SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd'T'hh:mm:ss.SSSXXX");
System.out.println(formatter.format(date));

formatter.setTimeZone(TimeZone.getTimeZone("UTC"));
System.out.println(formatter.format(date));

formatter.setTimeZone(TimeZone.getTimeZone("GMT"));
System.out.println(formatter.format(date));
```

```console
2019-08-18T05:38:52.380+02:00
2019-08-18T03:38:52.380Z
2019-08-18T03:38:52.380Z
```
